# Generated by Django 4.1.4 on 2022-12-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdata',
            name='ball',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='col_a',
            field=models.CharField(default='ffffff00', max_length=8),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='col_b',
            field=models.CharField(default='ff00ffff', max_length=8),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='cube',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='robot',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='ship',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='spider',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='ufo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='wave',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
