# Generated by Django 4.1.4 on 2022-12-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_playerdata_ball_playerdata_col_a_playerdata_col_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdata',
            name='coins',
            field=models.DecimalField(decimal_places=0, default=500, max_digits=10),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='energy',
            field=models.DecimalField(decimal_places=0, default=60, max_digits=3),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='gems',
            field=models.DecimalField(decimal_places=0, default=250, max_digits=10),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='stars',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
    ]
