# Generated by Django 4.1.4 on 2022-12-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_playerdata_coins_playerdata_energy_playerdata_gems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdata',
            name='level_world',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='max_energy',
            field=models.DecimalField(decimal_places=0, default=60, max_digits=6),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='trophies',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='energy',
            field=models.DecimalField(decimal_places=0, default=60, max_digits=6),
        ),
    ]
