# Generated by Django 4.1.4 on 2022-12-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_playerdata_level_world_playerdata_max_energy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerdata',
            name='col_a',
            field=models.CharField(default='1,1,0,1', max_length=16),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='col_b',
            field=models.CharField(default='0,1,1,1', max_length=16),
        ),
    ]
