extends Node

const SPECIAL_TILE_RING_YELLOW:       = 0
const SPECIAL_TILE_RING_PINK:         = 1
const SPECIAL_TILE_RING_BLUE:         = 2
const SPECIAL_TILE_RING_ORANGE:       = 3
const SPECIAL_TILE_RING_GREEN:        = 4

const SPECIAL_TILE_DASH_GREEN:        = 5
const SPECIAL_TILE_DASH_PINK:         = 6

const SPECIAL_TILE_BUMP_YELLOW:       = 7
const SPECIAL_TILE_BUMP_PINK:         = 8
const SPECIAL_TILE_BUMP_BLUE:         = 9
const SPECIAL_TILE_BUMP_ORANGE:       = 10

const SPECIAL_TILE_PORTAL_GRAV_NORMAL: = 11
const SPECIAL_TILE_PORTAL_GRAV_INV:    = 12
const SPECIAL_TILE_PORTAL_CUBE:        = 13
const SPECIAL_TILE_PORTAL_SHIP:        = 14
const SPECIAL_TILE_PORTAL_BALL:        = 15
const SPECIAL_TILE_PORTAL_UFO:         = 16
const SPECIAL_TILE_PORTAL_WAVE:        = 17
const SPECIAL_TILE_PORTAL_ROBOT:       = 18
const SPECIAL_TILE_PORTAL_SPIDER:      = 19

const SPECIAL_TILE_PORTAL_FLIP_VIEW:   = 20
const SPECIAL_TILE_PORTAL_NORMAL_VIEW: = 21
const SPECIAL_TILE_PORTAL_DUAL_CUBE:   = 22
const SPECIAL_TILE_PORTAL_DOUBLE_CUBE: = 23
